listen_addresses = '*'
max_connections = 40
shared_buffers = 64MB
effective_cache_size = 256MB
maintenance_work_mem = 32MB
checkpoint_completion_target = 0.9
wal_buffers = 2MB
default_statistics_target = 100
random_page_cost = 1.5
effective_io_concurrency = 50
work_mem = 2MB
min_wal_size = 64MB
max_wal_size = 512MB
log_timezone = 'UTC'
datestyle = 'iso, mdy'
timezone = 'UTC'
